# SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

{{- range $org := .Values.githubOrganizations }}
apiVersion: repo-guard.cloudoperators.dev/v1
kind: GithubOrganization
metadata:
  name: {{ $org.github }}--{{ $org.organization | replace "/" "-" | lower }}
  labels:
    repo-guard.cloudoperators.dev/addTeam: "{{ $org.addTeam | default "true" }}"
    repo-guard.cloudoperators.dev/removeTeam: "{{ $org.removeTeam | default "true" }}"
    repo-guard.cloudoperators.dev/addOrganizationOwner: "{{ $org.addOrganizationOwner | default "true" }}"
    repo-guard.cloudoperators.dev/removeOrganizationOwner: "{{ $org.removeOrganizationOwner | default "true" }}"
    repo-guard.cloudoperators.dev/addRepositoryTeam: "{{ $org.addRepositoryTeam | default "true" }}"
    repo-guard.cloudoperators.dev/removeRepositoryTeam: "{{ $org.removeRepositoryTeam | default "true" }}"
    repo-guard.cloudoperators.dev/dryRun: "{{ $org.dryRun | default "false" }}"
    {{- $ttl := (get $org "ttl") -}}
    {{- if not (kindIs "map" $ttl) }}{{- $ttl = dict -}}{{- end }}
    repo-guard.cloudoperators.dev/failedTTL: "{{ ((get $ttl "failed") | default $.Values.ttl.organization.failed) }}"
    repo-guard.cloudoperators.dev/completedTTL: "{{ ((get $ttl "completed") | default $.Values.ttl.organization.completed) }}"
  {{- $skipTeams := join "," $org.skipDefaultRepositoryTeams }}
  {{- if $skipTeams }}
  annotations:
    repo-guard.cloudoperators.dev/skipDefaultRepositoryTeams: "{{ $skipTeams }}"
  {{- end }}
spec:
  github: {{ $org.github }}
  organization: {{ $org.organization }}
  {{- if and $org.defaultPublicRepositoryTeams (gt (len $org.defaultPublicRepositoryTeams) 0) }}
  defaultPublicRepositoryTeams:
{{ toYaml $org.defaultPublicRepositoryTeams | indent 4 }}
  {{- end }}
  {{- if and $org.defaultPrivateRepositoryTeams (gt (len $org.defaultPrivateRepositoryTeams) 0) }}
  defaultPrivateRepositoryTeams:
{{ toYaml $org.defaultPrivateRepositoryTeams | indent 4 }}
  {{- end }}
  {{- if and $org.organizationOwnerTeams (gt (len $org.organizationOwnerTeams) 0) }}
  organizationOwnerTeams:
{{ toYaml $org.organizationOwnerTeams | indent 4 }}
  {{- end }}
  installationID: {{ $org.installationID | int64 }}
---
{{- end }}
