# SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

{{- range $org := .Values.githubOrganizations }}
  {{- if $org.teamRepositoryAssignments }}
    {{- range $ridx, $assign := $org.teamRepositoryAssignments }}
apiVersion: repo-guard.cloudoperators.dev/v1
kind: GithubTeamRepository
metadata:
  name: {{ $org.github }}--{{ $org.organization | replace "/" "-" | lower }}--{{ $assign.team | replace "_" "-" | replace " " "-" | lower }}--{{ $assign.permission }}
spec:
  github: {{ $org.github }}
  organization: {{ $org.organization }}
  team: {{ $assign.team }}
  repository:
{{ toYaml $assign.repositories | indent 4 }}
  permission: {{ $assign.permission }}
---
    {{- end }}
  {{- end }}
{{- end }}
