# SPDX-FileCopyrightText: 2025 SAP SE or an SAP affiliate company and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

{{ range .Values.ldaps }}
apiVersion: repoguard.cloudoperators.dev/v1
kind: {{ if .clusterScoped }}ClusterLDAPGroupProvider{{ else }}LDAPGroupProvider{{ end }}
metadata:
  name: {{ (.name | default "ldap") | lower }}
spec:
  secret: {{ (.name | default "ldap") | lower }}
  host: {{ .host }}
  baseDN:  {{ .baseDN }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ (.name | default "ldap") | lower }}
type: Opaque
data:
  bindDN: {{ .bindDN | b64enc }}
  bindPW: {{ .bindPW | b64enc }}
---
{{ end }}
