//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalMemberProviderConfig) DeepCopyInto(out *ExternalMemberProviderConfig) {
	*out = *in
	if in.LDAP != nil {
		in, out := &in.LDAP, &out.LDAP
		*out = new(GenericProvider)
		**out = **in
	}
	if in.LDAPGroupDepreceated != nil {
		in, out := &in.LDAPGroupDepreceated, &out.LDAPGroupDepreceated
		*out = new(LDAPGroup)
		**out = **in
	}
	if in.GenericHTTP != nil {
		in, out := &in.GenericHTTP, &out.GenericHTTP
		*out = new(GenericProvider)
		**out = **in
	}
	if in.Static != nil {
		in, out := &in.Static, &out.Static
		*out = new(GenericProvider)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalMemberProviderConfig.
func (in *ExternalMemberProviderConfig) DeepCopy() *ExternalMemberProviderConfig {
	if in == nil {
		return nil
	}
	out := new(ExternalMemberProviderConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenericExternalMemberProvider) DeepCopyInto(out *GenericExternalMemberProvider) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenericExternalMemberProvider.
func (in *GenericExternalMemberProvider) DeepCopy() *GenericExternalMemberProvider {
	if in == nil {
		return nil
	}
	out := new(GenericExternalMemberProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GenericExternalMemberProvider) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenericExternalMemberProviderList) DeepCopyInto(out *GenericExternalMemberProviderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GenericExternalMemberProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenericExternalMemberProviderList.
func (in *GenericExternalMemberProviderList) DeepCopy() *GenericExternalMemberProviderList {
	if in == nil {
		return nil
	}
	out := new(GenericExternalMemberProviderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GenericExternalMemberProviderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenericExternalMemberProviderSpec) DeepCopyInto(out *GenericExternalMemberProviderSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenericExternalMemberProviderSpec.
func (in *GenericExternalMemberProviderSpec) DeepCopy() *GenericExternalMemberProviderSpec {
	if in == nil {
		return nil
	}
	out := new(GenericExternalMemberProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenericExternalMemberProviderStatus) DeepCopyInto(out *GenericExternalMemberProviderStatus) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenericExternalMemberProviderStatus.
func (in *GenericExternalMemberProviderStatus) DeepCopy() *GenericExternalMemberProviderStatus {
	if in == nil {
		return nil
	}
	out := new(GenericExternalMemberProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenericProvider) DeepCopyInto(out *GenericProvider) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenericProvider.
func (in *GenericProvider) DeepCopy() *GenericProvider {
	if in == nil {
		return nil
	}
	out := new(GenericProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Github) DeepCopyInto(out *Github) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Github.
func (in *Github) DeepCopy() *Github {
	if in == nil {
		return nil
	}
	out := new(Github)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Github) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GithubAccountLink) DeepCopyInto(out *GithubAccountLink) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GithubAccountLink.
func (in *GithubAccountLink) DeepCopy() *GithubAccountLink {
	if in == nil {
		return nil
	}
	out := new(GithubAccountLink)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GithubAccountLink) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GithubAccountLinkList) DeepCopyInto(out *GithubAccountLinkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GithubAccountLink, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GithubAccountLinkList.
func (in *GithubAccountLinkList) DeepCopy() *GithubAccountLinkList {
	if in == nil {
		return nil
	}
	out := new(GithubAccountLinkList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GithubAccountLinkList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GithubAccountLinkSpec) DeepCopyInto(out *GithubAccountLinkSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GithubAccountLinkSpec.
func (in *GithubAccountLinkSpec) DeepCopy() *GithubAccountLinkSpec {
	if in == nil {
		return nil
	}
	out := new(GithubAccountLinkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GithubAccountLinkStatus) DeepCopyInto(out *GithubAccountLinkStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GithubAccountLinkStatus.
func (in *GithubAccountLinkStatus) DeepCopy() *GithubAccountLinkStatus {
	if in == nil {
		return nil
	}
	out := new(GithubAccountLinkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GithubList) DeepCopyInto(out *GithubList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Github, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GithubList.
func (in *GithubList) DeepCopy() *GithubList {
	if in == nil {
		return nil
	}
	out := new(GithubList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GithubList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GithubOrganization) DeepCopyInto(out *GithubOrganization) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GithubOrganization.
func (in *GithubOrganization) DeepCopy() *GithubOrganization {
	if in == nil {
		return nil
	}
	out := new(GithubOrganization)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GithubOrganization) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GithubOrganizationList) DeepCopyInto(out *GithubOrganizationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GithubOrganization, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GithubOrganizationList.
func (in *GithubOrganizationList) DeepCopy() *GithubOrganizationList {
	if in == nil {
		return nil
	}
	out := new(GithubOrganizationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GithubOrganizationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GithubOrganizationSpec) DeepCopyInto(out *GithubOrganizationSpec) {
	*out = *in
	if in.OrganizationOwnerTeams != nil {
		in, out := &in.OrganizationOwnerTeams, &out.OrganizationOwnerTeams
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DefaultPublicRepositoryTeams != nil {
		in, out := &in.DefaultPublicRepositoryTeams, &out.DefaultPublicRepositoryTeams
		*out = make([]GithubTeamWithPermission, len(*in))
		copy(*out, *in)
	}
	if in.DefaultPrivateRepositoryTeams != nil {
		in, out := &in.DefaultPrivateRepositoryTeams, &out.DefaultPrivateRepositoryTeams
		*out = make([]GithubTeamWithPermission, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GithubOrganizationSpec.
func (in *GithubOrganizationSpec) DeepCopy() *GithubOrganizationSpec {
	if in == nil {
		return nil
	}
	out := new(GithubOrganizationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GithubOrganizationStatus) DeepCopyInto(out *GithubOrganizationStatus) {
	*out = *in
	if in.Teams != nil {
		in, out := &in.Teams, &out.Teams
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PublicRepositories != nil {
		in, out := &in.PublicRepositories, &out.PublicRepositories
		*out = make([]GithubRepository, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PrivateRepositories != nil {
		in, out := &in.PrivateRepositories, &out.PrivateRepositories
		*out = make([]GithubRepository, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.OrganizationOwners != nil {
		in, out := &in.OrganizationOwners, &out.OrganizationOwners
		*out = make([]Member, len(*in))
		copy(*out, *in)
	}
	if in.OutOfPolicyRepositories != nil {
		in, out := &in.OutOfPolicyRepositories, &out.OutOfPolicyRepositories
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.OrganizationStatusTimestamp.DeepCopyInto(&out.OrganizationStatusTimestamp)
	in.Operations.DeepCopyInto(&out.Operations)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GithubOrganizationStatus.
func (in *GithubOrganizationStatus) DeepCopy() *GithubOrganizationStatus {
	if in == nil {
		return nil
	}
	out := new(GithubOrganizationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GithubOrganizationStatusOperations) DeepCopyInto(out *GithubOrganizationStatusOperations) {
	*out = *in
	if in.OrganizationOwnerOperations != nil {
		in, out := &in.OrganizationOwnerOperations, &out.OrganizationOwnerOperations
		*out = make([]GithubUserOperation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.GithubTeamOperations != nil {
		in, out := &in.GithubTeamOperations, &out.GithubTeamOperations
		*out = make([]GithubTeamOperation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RepositoryTeamOperations != nil {
		in, out := &in.RepositoryTeamOperations, &out.RepositoryTeamOperations
		*out = make([]GithubRepoTeamOperation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GithubOrganizationStatusOperations.
func (in *GithubOrganizationStatusOperations) DeepCopy() *GithubOrganizationStatusOperations {
	if in == nil {
		return nil
	}
	out := new(GithubOrganizationStatusOperations)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GithubRepoTeamOperation) DeepCopyInto(out *GithubRepoTeamOperation) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GithubRepoTeamOperation.
func (in *GithubRepoTeamOperation) DeepCopy() *GithubRepoTeamOperation {
	if in == nil {
		return nil
	}
	out := new(GithubRepoTeamOperation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GithubRepository) DeepCopyInto(out *GithubRepository) {
	*out = *in
	if in.Teams != nil {
		in, out := &in.Teams, &out.Teams
		*out = make([]GithubTeamWithPermission, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GithubRepository.
func (in *GithubRepository) DeepCopy() *GithubRepository {
	if in == nil {
		return nil
	}
	out := new(GithubRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GithubSpec) DeepCopyInto(out *GithubSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GithubSpec.
func (in *GithubSpec) DeepCopy() *GithubSpec {
	if in == nil {
		return nil
	}
	out := new(GithubSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GithubStatus) DeepCopyInto(out *GithubStatus) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GithubStatus.
func (in *GithubStatus) DeepCopy() *GithubStatus {
	if in == nil {
		return nil
	}
	out := new(GithubStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GithubTeam) DeepCopyInto(out *GithubTeam) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GithubTeam.
func (in *GithubTeam) DeepCopy() *GithubTeam {
	if in == nil {
		return nil
	}
	out := new(GithubTeam)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GithubTeam) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GithubTeamList) DeepCopyInto(out *GithubTeamList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GithubTeam, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GithubTeamList.
func (in *GithubTeamList) DeepCopy() *GithubTeamList {
	if in == nil {
		return nil
	}
	out := new(GithubTeamList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GithubTeamList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GithubTeamOperation) DeepCopyInto(out *GithubTeamOperation) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GithubTeamOperation.
func (in *GithubTeamOperation) DeepCopy() *GithubTeamOperation {
	if in == nil {
		return nil
	}
	out := new(GithubTeamOperation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GithubTeamRepository) DeepCopyInto(out *GithubTeamRepository) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GithubTeamRepository.
func (in *GithubTeamRepository) DeepCopy() *GithubTeamRepository {
	if in == nil {
		return nil
	}
	out := new(GithubTeamRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GithubTeamRepository) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GithubTeamRepositoryList) DeepCopyInto(out *GithubTeamRepositoryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GithubTeamRepository, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GithubTeamRepositoryList.
func (in *GithubTeamRepositoryList) DeepCopy() *GithubTeamRepositoryList {
	if in == nil {
		return nil
	}
	out := new(GithubTeamRepositoryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GithubTeamRepositoryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GithubTeamRepositorySpec) DeepCopyInto(out *GithubTeamRepositorySpec) {
	*out = *in
	if in.Repository != nil {
		in, out := &in.Repository, &out.Repository
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GithubTeamRepositorySpec.
func (in *GithubTeamRepositorySpec) DeepCopy() *GithubTeamRepositorySpec {
	if in == nil {
		return nil
	}
	out := new(GithubTeamRepositorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GithubTeamRepositoryStatus) DeepCopyInto(out *GithubTeamRepositoryStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GithubTeamRepositoryStatus.
func (in *GithubTeamRepositoryStatus) DeepCopy() *GithubTeamRepositoryStatus {
	if in == nil {
		return nil
	}
	out := new(GithubTeamRepositoryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GithubTeamSpec) DeepCopyInto(out *GithubTeamSpec) {
	*out = *in
	if in.ExternalMemberProvider != nil {
		in, out := &in.ExternalMemberProvider, &out.ExternalMemberProvider
		*out = new(ExternalMemberProviderConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GithubTeamSpec.
func (in *GithubTeamSpec) DeepCopy() *GithubTeamSpec {
	if in == nil {
		return nil
	}
	out := new(GithubTeamSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GithubTeamStatus) DeepCopyInto(out *GithubTeamStatus) {
	*out = *in
	in.TeamStatusTimestamp.DeepCopyInto(&out.TeamStatusTimestamp)
	if in.Operations != nil {
		in, out := &in.Operations, &out.Operations
		*out = make([]GithubUserOperation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = make([]Member, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GithubTeamStatus.
func (in *GithubTeamStatus) DeepCopy() *GithubTeamStatus {
	if in == nil {
		return nil
	}
	out := new(GithubTeamStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GithubTeamWithPermission) DeepCopyInto(out *GithubTeamWithPermission) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GithubTeamWithPermission.
func (in *GithubTeamWithPermission) DeepCopy() *GithubTeamWithPermission {
	if in == nil {
		return nil
	}
	out := new(GithubTeamWithPermission)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GithubUserOperation) DeepCopyInto(out *GithubUserOperation) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GithubUserOperation.
func (in *GithubUserOperation) DeepCopy() *GithubUserOperation {
	if in == nil {
		return nil
	}
	out := new(GithubUserOperation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LDAPGroup) DeepCopyInto(out *LDAPGroup) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LDAPGroup.
func (in *LDAPGroup) DeepCopy() *LDAPGroup {
	if in == nil {
		return nil
	}
	out := new(LDAPGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LDAPGroupProvider) DeepCopyInto(out *LDAPGroupProvider) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LDAPGroupProvider.
func (in *LDAPGroupProvider) DeepCopy() *LDAPGroupProvider {
	if in == nil {
		return nil
	}
	out := new(LDAPGroupProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LDAPGroupProvider) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LDAPGroupProviderList) DeepCopyInto(out *LDAPGroupProviderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LDAPGroupProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LDAPGroupProviderList.
func (in *LDAPGroupProviderList) DeepCopy() *LDAPGroupProviderList {
	if in == nil {
		return nil
	}
	out := new(LDAPGroupProviderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LDAPGroupProviderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LDAPGroupProviderSpec) DeepCopyInto(out *LDAPGroupProviderSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LDAPGroupProviderSpec.
func (in *LDAPGroupProviderSpec) DeepCopy() *LDAPGroupProviderSpec {
	if in == nil {
		return nil
	}
	out := new(LDAPGroupProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LDAPGroupProviderStatus) DeepCopyInto(out *LDAPGroupProviderStatus) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LDAPGroupProviderStatus.
func (in *LDAPGroupProviderStatus) DeepCopy() *LDAPGroupProviderStatus {
	if in == nil {
		return nil
	}
	out := new(LDAPGroupProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Member) DeepCopyInto(out *Member) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Member.
func (in *Member) DeepCopy() *Member {
	if in == nil {
		return nil
	}
	out := new(Member)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StaticGroup) DeepCopyInto(out *StaticGroup) {
	*out = *in
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StaticGroup.
func (in *StaticGroup) DeepCopy() *StaticGroup {
	if in == nil {
		return nil
	}
	out := new(StaticGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StaticMemberProvider) DeepCopyInto(out *StaticMemberProvider) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StaticMemberProvider.
func (in *StaticMemberProvider) DeepCopy() *StaticMemberProvider {
	if in == nil {
		return nil
	}
	out := new(StaticMemberProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StaticMemberProvider) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StaticMemberProviderList) DeepCopyInto(out *StaticMemberProviderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StaticMemberProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StaticMemberProviderList.
func (in *StaticMemberProviderList) DeepCopy() *StaticMemberProviderList {
	if in == nil {
		return nil
	}
	out := new(StaticMemberProviderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StaticMemberProviderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StaticMemberProviderSpec) DeepCopyInto(out *StaticMemberProviderSpec) {
	*out = *in
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]StaticGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StaticMemberProviderSpec.
func (in *StaticMemberProviderSpec) DeepCopy() *StaticMemberProviderSpec {
	if in == nil {
		return nil
	}
	out := new(StaticMemberProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StaticMemberProviderStatus) DeepCopyInto(out *StaticMemberProviderStatus) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StaticMemberProviderStatus.
func (in *StaticMemberProviderStatus) DeepCopy() *StaticMemberProviderStatus {
	if in == nil {
		return nil
	}
	out := new(StaticMemberProviderStatus)
	in.DeepCopyInto(out)
	return out
}
