---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - repoguard.sap
  resources:
  - clustergenericexternalmemberproviders
  - clusterldapgroupproviders
  - clusterstaticmemberproviders
  - genericexternalmemberproviders
  - githubaccountlinks
  - githuborganizations
  - githubs
  - githubteamrepositories
  - githubteams
  - ldapgroupproviders
  - staticmemberproviders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - repoguard.sap
  resources:
  - clustergenericexternalmemberproviders/finalizers
  - clusterldapgroupproviders/finalizers
  - clusterstaticmemberproviders/finalizers
  - genericexternalmemberproviders/finalizers
  - githubaccountlinks/finalizers
  - githuborganizations/finalizers
  - githubs/finalizers
  - githubteamrepositories/finalizers
  - githubteams/finalizers
  - ldapgroupproviders/finalizers
  - staticmemberproviders/finalizers
  verbs:
  - update
- apiGroups:
  - repoguard.sap
  resources:
  - clustergenericexternalmemberproviders/status
  - clusterldapgroupproviders/status
  - clusterstaticmemberproviders/status
  - genericexternalmemberproviders/status
  - githubaccountlinks/status
  - githuborganizations/status
  - githubs/status
  - githubteamrepositories/status
  - githubteams/status
  - ldapgroupproviders/status
  - staticmemberproviders/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - greenhouse.sap
  resources:
  - teams
  verbs:
  - get
  - list
  - watch
