name: Cut Release

on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'Version bump type'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  cut-release:
    uses: cloudoperators/common/.github/workflows/shared-release.yaml@main
    with:
      bump: ${{ inputs.bump }}
      chart-path: charts/repo-guard/Chart.yaml
      bump-make-version: true
      dispatch-greenhouse-extensions: true
      plugin-name: repo-guard
    secrets:
      release-token: ${{ secrets.RELEASE_GH_TOKEN_PR }}
