name: Cut Release

on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'Version bump type'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  cut-release:
    uses: cloudoperators/common/.github/workflows/shared-release.yaml@main
    permissions:
      contents: write
    with:
      bump: ${{ inputs.bump }}
      chart-path: charts/repo-guard/Chart.yaml
      makefile-path: Makefile
      bump-make-version: true
      dispatch-greenhouse-extensions: true
      plugin-name: repo-guard
      environment: release
    secrets:
      release-token: ${{ secrets.RELEASE_GH_TOKEN_PR }}
      dispatch-app-id: ${{ secrets.CLOUDOPERATOR_APP_ID }}
      dispatch-app-private-key: ${{ secrets.CLOUDOPERATOR_APP_PRIVATE_KEY }}